using System;
using System.Runtime.InteropServices;
using Unity.Collections;
using Unity.Mathematics;

namespace Simular.VaporWave.Experimental {
  /// <summary>
  /// Stores chunk data during creation of that chunk.
  /// </summary>
  [Serializable]
  [StructLayout(LayoutKind.Sequential)]
  public struct ChunkCreationData {
    /// <summary>
    /// The location of the chunk in the world.
    /// </summary>
    public int3 location;

    /// <summary>
    /// The mesh data generated by the meshing algorithm.
    /// </summary>
    public NativeList<float3> mesh;

    /// <summary>
    /// The volume data for the chunk generated.
    /// </summary>
    public NativeArray<float> volume;



    public ChunkCreationData(int3 location, NativeList<float3> mesh, NativeArray<float> volume) {
      this.location = location;
      this.mesh = mesh;
      this.volume = volume;
    }
  }
}
